# Generated by Django 4.1 on 2022-08-24 08:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.CharField(max_length=50)),
                ('client', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=14)),
                ('plates_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('edge_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cutting_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('edging_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('others_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('order_ready', models.BooleanField(default=False)),
                ('order_taken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('Egger', 'Egger'), ('Kronospan', 'Kronospan'), ('Other', 'Other')], default='Egger', max_length=10)),
                ('material', models.CharField(max_length=50)),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordered', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('cutted', models.BooleanField(default=False)),
                ('edged', models.BooleanField(default=False)),
                ('cutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Bank', 'Bank')], default='Cash', max_length=10)),
                ('cutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.order')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.order')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='n/a', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('cutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.order')),
            ],
        ),
        migrations.CreateModel(
            name='Edging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edging_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.order')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(max_length=50)),
                ('color_code', models.CharField(default='', max_length=50)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordered', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('cutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.order')),
            ],
        ),
    ]
