# Generated by Django 4.1 on 2022-09-09 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_edge_visible_order_invoice_alter_cutting_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
