# Generated by Django 4.1 on 2022-10-27 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_payment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='from_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.49)]),
        ),
        migrations.AlterField(
            model_name='edge',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.49)]),
        ),
        migrations.AlterField(
            model_name='edging',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.49)]),
        ),
        migrations.AlterField(
            model_name='other',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.49)]),
        ),
        migrations.AlterField(
            model_name='plate',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.49)]),
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(default='N/A', max_length=100)),
                ('operation', models.CharField(default='N/A', max_length=100)),
                ('what', models.CharField(default='N/A', max_length=100)),
                ('current_state', models.CharField(default='', max_length=100)),
                ('new_state', models.CharField(default='', max_length=100)),
                ('cutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.order')),
            ],
        ),
    ]
