# Generated by Django 4.2.16 on 2025-09-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_rename_id_order_id_change_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='cutID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='cutting',
            old_name='cutID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='cutID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='edging',
            old_name='cutID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='cutID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='other',
            old_name='cutID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='cutID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='cutID',
            new_name='order_id',
        ),
    ]
