# Generated by Django 4.2.16 on 2025-09-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_rename_cutid_change_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='table.order'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='table.order'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='table.order'),
        ),
        migrations.AlterField(
            model_name='edging',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='table.order'),
        ),
        migrations.AlterField(
            model_name='note',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='table.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(choices=[('Internal', 'Поръчка'), ('External', 'Оферта')], default='Internal', max_length=50),
        ),
        migrations.AlterField(
            model_name='other',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='table.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='table.order'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='table.order'),
        ),
    ]
