# Generated by Django 4.2.16 on 2025-10-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_alter_change_order_id_alter_cutting_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(choices=[('Internal', 'Поръчка'), ('External', 'Оферта')], default='External', max_length=50),
        ),
    ]
