# Generated by Django 4.2.16 on 2026-01-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_alter_order_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='what',
            new_name='related_item',
        ),
    ]
