# Generated by Django 4.2.16 on 2026-01-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0009_rename_what_change_related_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'в брой'), ('Card', 'банкова карта'), ('Bank', 'банков превод')], default='Cash', max_length=10),
        ),
    ]
