# Generated by Django 4.2.16 on 2026-01-23 21:57

from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Coalesce


def recalculate_order_balances(apps, schema_editor):
    Order = apps.get_model('table', 'Order')

    Order.objects.update(
        balance=Coalesce(F('total_price'), Value(0)) - Coalesce(F('paid'), Value(0))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0010_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RunPython(recalculate_order_balances, migrations.RunPython.noop),
    ]
