# Generated by Django 5.1.2 on 2026-07-14

from django.db import migrations, models


def backfill_order_type_from_client(apps, schema_editor):
    Order = apps.get_model("table", "Order")

    manager = Order._base_manager
    manager.filter(client="Internal").update(order_type="order")
    manager.filter(client="External").update(order_type="offer")
    manager.filter(order_type="").update(order_type="order")
    manager.filter(order_type__isnull=True).update(order_type="order")


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0011_fix_order_balance_calculation"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("order", "Поръчка"), ("offer", "Оферта")],
                default="order",
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_order_type_from_client, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="order",
            name="client",
        ),
    ]
