# Generated by Django 5.1.2 on 2026-07-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0012_order_type_cutover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('order', 'Поръчка'), ('offer', 'Оферта')], default='offer', max_length=10),
        ),
    ]
