# Generated by Django 4.2.16 on 2025-10-16 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vitrine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=14)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('order_ready', models.BooleanField(default=False)),
                ('order_taken', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frame_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('glass_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('holes_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('seals_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.49)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vitrine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.vitrine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Bank', 'Bank')], default='Cash', max_length=10)),
                ('vitrine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.vitrine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.49)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(max_length=50)),
                ('vitrine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.vitrine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direction', models.CharField(choices=[('down', 'отдолу'), ('up', 'отгоре')], default='down', max_length=10)),
                ('position_x', models.CharField(choices=[('left', 'лява'), ('right', 'дясна')], default='right', max_length=10)),
                ('position_y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000)])),
                ('quantity', models.IntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)])),
                ('vitrine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.vitrine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('glass_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)])),
                ('vitrine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.vitrine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.49)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profile_color', models.CharField(choices=[('Black', 'Черен'), ('Matte', 'Мат'), ('Inox', 'Инокс')], default='Black', max_length=10)),
                ('length', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000)])),
                ('width', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000)])),
                ('vitrine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.vitrine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
