# Generated by Django 4.2.16 on 2026-01-07 00:08

import common.mixins.workflow.WorkflowModelMixin
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='profile_color',
            new_name='profile_type',
        ),
        migrations.RemoveField(
            model_name='hole',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='hole',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='hole',
            name='position_y',
        ),
        migrations.RemoveField(
            model_name='vitrine',
            name='frame_total',
        ),
        migrations.RemoveField(
            model_name='vitrine',
            name='other_total',
        ),
        migrations.AddField(
            model_name='frame',
            name='glass_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='holes_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='frame',
            name='holes_position',
            field=models.CharField(choices=[('length', 'дължина'), ('width', 'широчина')], default='length', max_length=10),
        ),
        migrations.AddField(
            model_name='glass',
            name='frame_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.frame'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hole',
            name='frame_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.frame'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hole',
            name='holes_position',
            field=models.CharField(choices=[('length', 'дължина'), ('width', 'широчина')], default='length', max_length=10),
        ),
        migrations.AddField(
            model_name='seal',
            name='frame_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.frame'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seal',
            name='seal_type',
            field=models.CharField(choices=[('Black', 'Черно'), ('White', 'Бяло')], default='Black', max_length=10),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='add_hole_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='black_profile_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='black_seal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='frames_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='inox_profile_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='manufacturing_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='manufacturing_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='matte_profile_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='others_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='white_seal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='frame',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='glass',
            name='glass_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='glass',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='hole',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='glass_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='holes_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='seals_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(default='n/a', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('vitrine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.vitrine')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, common.mixins.workflow.WorkflowModelMixin),
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(default='N/A', max_length=100)),
                ('operation', models.CharField(default='N/A', max_length=100)),
                ('related_item', models.CharField(default='N/A', max_length=100)),
                ('current_state', models.CharField(default='', max_length=100)),
                ('new_state', models.CharField(default='', max_length=100)),
                ('vitrine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vitrine.vitrine')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, common.mixins.workflow.WorkflowModelMixin),
        ),
    ]
