# Generated by Django 4.2.16 on 2026-01-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_rename_profile_color_frame_profile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='profile_type',
            field=models.CharField(choices=[('Black', 'Черен'), ('Matte', 'Матов'), ('Inox', 'Инокс')], default='Black', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'в брой'), ('Card', 'банкова карта'), ('Bank', 'банков превод')], default='Cash', max_length=10),
        ),
    ]
