# Generated by Django 5.1.2 on 2026-07-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_alter_frame_profile_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='auto_calculate_seal',
            field=models.BooleanField(default=True),
        ),
    ]
