# Generated by Django 5.1.2 on 2026-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_frame_auto_calculate_seal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrine',
            name='black_seal_custom_amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='vitrine_manual_seal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vitrine',
            name='white_seal_custom_amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
    ]
