# Generated by Django 5.1.2 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitrine", "0005_vitrine_black_seal_custom_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitrine",
            name="order_type",
            field=models.CharField(
                choices=[("order", "Поръчка"), ("offer", "Оферта")],
                default="order",
                max_length=10,
            ),
        ),
    ]
