# Generated by Django 5.1.2 on 2026-07-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0007_alter_vitrine_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='glass_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
